---

model: starcoder-bigcode
url: https://huggingface.co/bigcode/starcoder
sampling:
  temperature: 0.7
  repetition_penalty: 1.0
  top_p: 0.95
  top_k: 40  # Applicable to llama.cpp only
  repeat_last_n: 64  # Applicable to llama.cpp only
  n_batch: 512  # Applicable to llama.cpp only
generation:
  mean_gen_len: 128  # Applicable to mlc only
  max_gen_len: 4096
  max_window_size: 8192
  vocab_size: 49152  # Applicable to mlc only
prompt:  # Used in llama.cpp, taken from mlc
  text: ""
  in_prefix: ""
  in_suffix: ""
  reverse: ""